### ISSUE TITLE
Extract response generator from ErrorCatcher middleware

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/error-handler#129]
Move `ErrorCatcher` logic to `ErrorResponseFactory`.
https://github.com/olegbaturin/yii3-error-handler/blob/error-response-factory/src/ErrorResponseFactory.php
https://github.com/olegbaturin/yii3-error-handler/blob/error-response-factory/src/Middleware/ErrorCatcher.php

Add `ErrorResponseFactoryInterface`, so application can implements own `ErrorResponseFactory`, and `ExceptionResponder` middleware with custom exception parsers can become a part of `ErrorResponseFactory`.
https://github.com/olegbaturin/yii3-app-api/blob/master/src/Renderer/Error/ErrorResponseFactory.php

**Comment by samdark** [comment]
Good idea. Want to make a pull request?

**Comment by vjik** [comment]
Done by #133
