### ISSUE TITLE
\Yiisoft\ErrorHandler\ErrorCatcher::getContentType can't recognise my accept header

### ISSUE THREAD

**Issue by epifrin** [yiisoft/error-handler#15]
### What steps will reproduce the problem?
Try to open page with error and with Accept Header

Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

### What is the expected result?

I expect to see html page with error

### What do you get instead?

I got plain text with html code of error page

HeaderHelper::getSortedAcceptTypes throws error:
Message: `Invalid input: q=0.9,image/webp,*/*;q=0.8`
File: `vendor\yiisoft\error-handler\src\HeaderHelper.php`
Line: `96`

### Additional info

| Q                | A
| ---------------- | ---
| PHP version      |  7.4.11
| Browser            | Firefox

**Comment by samdark** [comment]
@roxblnfk would you please take a look?

**Comment by roxblnfk** [comment]
> @roxblnfk would you please take a look?

I can not reproduce this bug. I need completly test for this case

**Comment by samdark** [comment]
@roxblnfk there's now a test.

**Comment by roxblnfk** [comment]
> @roxblnfk there's now a test.

The test demonstrates incorrect type detection, however the mentioned error is not reproduced

> HeaderHelper::getSortedAcceptTypes throws error:
> Message: Invalid input: q=0.9,image/webp,*/*;q=0.8
> File: vendor\yiisoft\error-handler\src\HeaderHelper.php
> Line: 96
