### ISSUE TITLE
Solution: add support code syntax and improve appearance

### ISSUE THREAD

**Issue by vjik** [yiisoft/error-handler#44]
![image](https://user-images.githubusercontent.com/525501/119383178-afdfe100-bccb-11eb-8fac-4cd09b4b7f08.png)

Text in quotation marks is not highlighted as code.
Also, i think, need increase line height for solution.

**Comment by samdark** [comment]
Using markdown should be even better but then we should deal with encoding potential XSS etc. Makes it a bit more complicated.

**Comment by rustamwin** [comment]
https://github.com/yiisoft/friendly-exception/pull/15
