### ISSUE TITLE
Add ErrorRendererResolver

### ISSUE THREAD

**Issue by xepozz** [yiisoft/error-handler#5]
Needs to implement `ErrorRendererResolver` that will gives needed `ErrorRenderer` depending on the header `Accept-Content-Type`

Resolving is needed in https://github.com/yiisoft/yii-demo/blob/ca1a039b3c16a260367a78f33875379848e2ba0d/public/index.php#L24

**Comment by samdark** [comment]
Already done in ErrorCathcer.
